### ISSUE TITLE
Course selection for sync

### ISSUE THREAD

**Issue by thetric** [thetric/ilias-downloader#3]
As an user, I want to choose the courses to be included in the sync to download only the contents I am interested in.

- [ ] show available courses
- [ ] edit selection
- [ ] show my selection
- [ ] only selected courses are synced
- [ ] selection is persisted

**Comment by jeysal** [comment]
Does the persistence part work yet?
For me, version 1.0 stores an empty array in the `.ilias-downloader.json` file and thus no courses are synced unless I run course selection again.
